### ISSUE TITLE
Regression: Header-Properties not displayed in messagebrowser when using columnsets

### ISSUE THREAD

**Issue by blackfoxoh** [jmstoolbox/jmstoolbox#104] opened 2021-01-20 09:05 UTC
## Specifications
- JMSToolBox version: 5.9.0
- OS (Name, version, 32/64bits): Windows 10, 64Bit
- Q provider (kind, version) : IBM MQ

## Expected Behavior
Using columnsets, the message-browser should display the referenced header-properties in the table-view.
I just updated from version 5.0.0 to 5.9.0. I had a quick look at the changelogs since version 5.0.0 and found #40 in version 5.1.0. So I checked with 5.1.0 => doesn't work with 5.1.0 either. I guess #40 introduced this regression...

## Actual Behavior
only standard JMS-Headers are displayed, as far as I can tell

## Steps to Reproduce the Problem
  1. JMS-Message with custom header-properties in a queue
  2. use a custom columnset for the queue, referencing this custom property
  3. browse the queue using the columnset defined
  4. --> column isn't populated anymore

**Comment by titou10titou10** [comment] 2021-01-22 13:21
I can't reproduce the bug...
Could you describe it in mopre details?
Also, maybe it is due to the upgrade?
Could you create a columnset with the same properties as the one you created in JTB v5.0.0 and see if it work?

**Comment by blackfoxoh** [comment] 2021-01-25 07:31
I investigated a bit further and have to admit the "steps to reproduce" aren't correct. In fact it seems to be related with the upgrade.
I created a new columnset -> worked as expected.
Then I had a look in the resulting settings of "columnssets.xml". The difference from the old cs to the new cs is, that there is a new element "<origin>USER_PROPERTY</origin>" for each column of kind USER_PROPERTY. 
Adding this in the xml + restart of JTB helps, or opening the settings in JTB and selecting a column and hit "Add/Modify" fixes it for that column as well. Both workarounds have to be done for each defined column in each columnset.
If you would like to fix it you may add that xml element to all defined columnset-columns of kind user_property when it is missing. I don't know how much users are affected of this - for my case I'm fine with fixing it manually in my config. I would suggest to fix it if it isn't too much effort or otherwise add a note on this in the release-notes or wiki....

**Comment by titou10titou10** [comment] 2021-01-29 13:28
@blackfoxoh thanks for reporting and glad your problem is fixed
I'll close this ticket as I don't think there are many people affected with the problem and the "solution" is described on here anyway

**Closed by titou10titou10** 2021-01-29 13:28 UTC
Labels: feature/columns_sets, kind/information_needed
