### ISSUE TITLE
JMSToolbox does not connect to WAS v8.5.5.12 installed on my machine

### ISSUE THREAD

**Issue by MohanlalG** [jmstoolbox/jmstoolbox#3] opened 2018-03-15 14:21 UTC
## Specifications
- JMSToolBox version: 4.8.0
- OS (Name, version, 32/64bits): Windows 7 64 bit 
- Q provider (kind, version) : IBM Websphere / IBM Wesbsphere SIB

## Steps to Reproduce the Problem

  1. Install WAS v8.5.5.12 and JMSToolbox v4.8.0
  1. Configured IBM Websphere Q Manager with 3 jars.
  1. Created a Session by entering Session Name, Queue Manager and a Host and Port number.
![session page screen shot](https://user-images.githubusercontent.com/37409499/37468711-a480c48a-285b-11e8-8910-944812511496.png)
![qmanager](https://user-images.githubusercontent.com/37409499/37468769-bee82d2c-285b-11e8-837e-31d3265304cd.png)
![error screen shot](https://user-images.githubusercontent.com/37409499/37468842-e35fda7e-285b-11e8-8a08-75036e34fcbb.png)
![properties](https://user-images.githubusercontent.com/37409499/37468991-30e1a480-285c-11e8-98da-e1bce60cb570.png)

**Comment by titou10titou10** [comment] 2018-03-15 14:45
It seems you are mixing the setup of the **WebSphere SIB** session type and the **WebSphere JMS** session type, as you selected the WebSphere JMS as session type but added the jars required for the SIB connector.
With the  **WebSphere SIB**  connector, JMSToolBox connects to the embedded Q provider in WebSphere, this is the recommended way as you'll see **all** the destinitations defined in the internal SIB. For using this session type, follow the instructions  [here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.3-Setup-for-IBM-WebSphere-SIB)
With the  **WebSphere JMS**  session type, JMSToolBox connects to the JNDI component in WebSphere. JMSToolBox will only lists the destinations defined in the JNDI space. For this session type follow the instructions [here](https://github.com/jmstoolbox/jmstoolbox/wiki/2.4-Setup-for-IBM-WebSphere-JMS)

**Comment by MohanlalG** [comment] 2018-03-15 15:56
Hello Denis,

Thank you very much for your quick response.

I did follow the steps given for WebSphere SIB connector and I am still not able to connect JMSToolbox with WAS 8.5.5.12.

Please find screen-shots of settings and the error that I get.

Please help.

Thanks,
MohanlalG

![webspheresib](https://user-images.githubusercontent.com/37409499/37474897-54c093d6-2869-11e8-90c8-37d047492af7.png)
![error](https://user-images.githubusercontent.com/37409499/37474899-550d7a98-2869-11e8-983e-2a8600031486.png)
![connections](https://user-images.githubusercontent.com/37409499/37474900-55579b8c-2869-11e8-9905-b8963f53b0d3.png)
![properties](https://user-images.githubusercontent.com/37409499/37474901-55b3f29c-2869-11e8-85b6-e3b90f496a8a.png)

**Comment by MohanlalG** [comment] 2018-03-15 15:58
![jars](https://user-images.githubusercontent.com/37409499/37475026-a1a23286-2869-11e8-8aa2-1adf69172a7f.png)

I have also attached the screen-shot of the JARs configured for WebSphere SIB. Thanks !!

**Comment by titou10titou10** [comment] 2018-03-15 16:18
On your print screen,s. in the properties folder, the `busName` is most likely wrong
You'll find the name of the SIB you created in WebSphere by using the WAS console, in the `Service integration -> Buses. `section

**Comment by MohanlalG** [comment] 2018-03-16 14:41
Still not able to connect JMSToolbox with Websphere AS on my local. PFA screen-shots.
![jars](https://user-images.githubusercontent.com/37409499/37526689-f6439b18-2927-11e8-80c8-6ca3e193ee45.png)
![connection](https://user-images.githubusercontent.com/37409499/37526706-02bbfdd6-2928-11e8-81b8-1bc99a72ade3.png)
![properties](https://user-images.githubusercontent.com/37409499/37526720-0aa08d14-2928-11e8-94e5-84c2c0129bac.png)
![invalidaddressconnectionerror](https://user-images.githubusercontent.com/37409499/37526733-127a2c3e-2928-11e8-8f1c-75c7f3891eee.png)
[orbtrc.16032018.2002.37.txt](https://github.com/jmstoolbox/jmstoolbox/files/1819586/orbtrc.16032018.2002.37.txt)

Requesting your help here. Thanks !!

**Comment by titou10titou10** [comment] 2018-03-16 16:22
So you switch back to **WebSphere JMS**...Is that what you want?
Did you follow the setup manual as explained before?
Does the server at address `"IBM263-PC0CQCTC.in.ibm.com"` has it's `"BOOTSTRAP_ADDRESS"` port set to `"2809"` ?
Are that server and port accessible from where JMSToolBox runs?
What is address `9.199.110.58 `(port=0)  seen in the log file you joined?

**Comment by MohanlalG** [comment] 2018-03-16 17:58
Thank you very much for your quick response. Appreciate your support.
Yes I have switched back to WebSphere JMS. Yes I want to connect JMSToolbox with WebSphere Application Server using WebSphere JMS.
Yes, the WebSphere server running at hostname - IBM263-PC0CQCTC.in.ibm.com - has its BOOSTRAP_ADDRESS port set to 2809 and this port is accessible when hit by Telnet. Please find screen-shot of the portdef.properties file that holds the port number of various ends.
Yes, I am able to telnet server host and port number. FYI - Both the JMSToolbox and server are running on my local.
I tried to change hostname with portnumber on the Connection tab to see if it connects. But it failed. But still it fails.
![portdefinitions](https://user-images.githubusercontent.com/37409499/37536788-8633491a-2943-11e8-9188-e3a8b125c838.png)

Please help. Thank you.

**Comment by titou10titou10** [comment] 2018-06-19 11:22
Closing as not able to reproduce and there is great chances it is not related to JMSToolBox
Please reopen this bug if it still a problem

**Closed by titou10titou10** 2018-06-19 11:22 UTC
Labels: qm:websphere_jndi, qm:websphere_sib, wontfix
